services:
  # MongoDB Seu Data Lake oficial
  mongodb:
    image: mongo:latest
    container_name: mongodb_rag
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      # Definindo o banco inicial como rag_database para bater com o script
      MONGO_INITDB_DATABASE: rag_database

volumes:
  mongo_data:
